jvb_memories_main:
    resource: "@JvbMemoriesMainBundle/Resources/config/routing.yml"
    prefix:   /

jvb_memories_user:
    resource: "@JvbMemoriesUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"